
- hosts: all
  become: true
  tasks:
  
  - name: Install updates (Ubuntu)
    tags: update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: '0755'
      owner: root
      group: root
    register: terraform_install

- hosts: all
  become: true
  tasks:
  - name:  copy default html file for site
    tags: html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'

  - name: Apache2 & php support Install package
    tags: packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

