---
- name: Update all servers
  hosts: all
  gather_facts: yes
  tasks:

    - name: Update Ubuntu packages
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Check if Ubuntu reboot is required
      when: ansible_os_family == "Debian"
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot Ubuntu if needed
      when: ansible_os_family == "Debian" and reboot_required_file.stat.exists
      reboot:
        msg: "Rebooting due to updates"
        pre_reboot_delay: 5
        reboot_timeout: 700

    - name: Update Windows packages
      when: ansible_os_family == "Windows"
      win_shell: |
        if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {
            Install-Module -Name PSWindowsUpdate -Force -Confirm:$false
        }
        Import-Module PSWindowsUpdate
        $updates = Get-WindowsUpdate -AcceptAll -Install -IgnoreReboot
        if ($updates | Where-Object {$_.RebootRequired -eq $true}) {
            Restart-Computer -Force
        }
